export const CALCULATE_GENERAL_HOURS = 'CALCULATE_GENERAL_HOURS';
export const CALCULATE_TOTAL_HOURS = 'CALCULATE_TOTAL_HOURS';
export const CALCULATE_PROBABILITY_TIME = 'CALCULATE_PROBABILITY_TIME';

export const ADD_DASHBOARD_STATE = 'ADD_DASHBOARD_STATE';
export const CHANGE_GENERAL_ESTIMATE_INFO = 'CHANGE_GENERAL_ESTIMATE_INFO';
