export const ADD_NEW_TASK = 'ADD_NEW_TASK';
export const ADD_NEW_SUBTASK = 'ADD_NEW_SUBTASK';
export const REMOVE_TASK = 'REMOVE_TASK';
export const MODIFY_TASK = 'MODIFY_TASK';

export const SET_PARENT_TASK_ID = 'SET_PARENT_TASK_ID';
export const REMOVE_PARENT_TASK_ID = 'REMOVE_PARENT_TASK_ID';

export const ADD_HEADER_INFO_DATA = 'ADD_HEADER_INFO_DATA';
export const ADD_HEADER_INFO_TECHNOLOGIES = 'ADD_HEADER_INFO_TECHNOLOGIES';


export const CHANGE_MONEY_RATE = 'CHANGE_MONEY_RATE';
export const CALC_DEV_HOURS = 'CALC_DEV_HOURS';
export const ADD_ESTIMATE_OPTIONS = 'ADD_ESTIMATE_OPTIONS';
export const ADD_CLIENT_CONTACT_DATA = 'ADD_CLIENT_CONTACT_DATA';

export const APPLY_STATE = 'APPLY_STATE';
export const UPDATE_DEVELOPMENT_TIME = 'UPDATE_DEVELOPMENT_TIME';

export const RECALCULATION = 'RECALCULATION';
