export const ADD_NEW_TASK = 'ADD_NEW_TASK';
export const ADD_NEW_SUBTASK = 'ADD_NEW_SUBTASK';
export const REMOVE_TASK = 'REMOVE_TASK';
export const MODIFY_TASK = 'MODIFY_TASK';

export const ADD_HEADER_INFO_DATA = 'ADD_HEADER_INFO_DATA';
